version: "3.7"
services:
  front-envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile

  emulator:
    build:
      context: .
      dockerfile: emulator.Dockerfile
    shm_size: 1G
    volumes:
    - type: bind
      source: /home/kamil/.android/adbkey
      target: /root/.android/adbkey
    - type: bind
      source: /home/kamil/.android/adbkey.pub
      target: /root/.android/adbkey.pub
  jwt_signer:
    build:
      context: .
      dockerfile: jwt_signer.Dockerfile
  nginx:
    build:
      context: ./android-emulator-container-scripts/js
      dockerfile: docker/nginx.Dockerfile
